In [14]:
from IPython.display import Image
from IPython.core.display import HTML

import numpy as np
import gym
import random
import time

In [15]:
env_name = "FrozenLake-v1"
env = gym.make(env_name)

In [16]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [17]:
action_size

4

In [18]:
state_size

16

In [19]:
qtable = np.zeros((state_size, action_size))
qtable

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
total_episodes = 15000      # total episodes
learning_rate = 0.8         # learning rate 
max_steps = 99              # max steps per episode
gamma = 0.95                # discounting rate

In [21]:
# exploration paramerers
epsilon = 1.0                 # exploration rate
max_epsilon = 1.0             # exploration probability at start
min_epsilon = 0.01          # minimum exploration probability
decay_rate = 0.05           # exponential decay rate for exploration probability

In [26]:
rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        trade_off = random.uniform(0, 1)
           
        if trade_off > epsilon:
            action = np.argmax(qtable[state,:])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :] - qtable[state, action]))
        
        
        total_rewards += reward
        state = new_state
        
        if done == True:
            break
        
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_rewards)

print("Score over time:", str(sum(rewards)/total_episodes))
print(qtable)
        

Score over time: 0.18286666666666668
[[1.02374378e+00 1.02434459e+00 1.02469195e+00 1.02470957e+00]
 [8.37033595e-01 7.92286959e-01 7.82178399e-01 1.02470957e+00]
 [9.41035411e-01 9.70928116e-01 3.97640475e-01 1.02470957e+00]
 [8.37802535e-01 1.01394319e+00 8.27036577e-01 1.02470957e+00]
 [1.02315554e+00 2.26564791e-01 1.57616196e-01 1.82548547e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.70697848e-03 1.72295190e-06 1.00319579e+00 7.59023552e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.66487481e-01 1.89360753e-01 6.08163394e-03 1.01652179e+00]
 [2.28956893e-01 1.01328821e+00 5.26055259e-02 2.10979533e-01]
 [1.00637969e+00 1.36761708e-02 2.05160559e-01 1.78573244e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.89113616e-01 2.05215005e-01 1.00581134e+00 2.48398706e-01]
 [7.79895636e-01 1.04139310e+00 8.12570350e-01 5.30977208e-01]
 [0.00000000e+00 0

In [ ]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    
    print('Episode: ', episode)
    
    for step in range(max_steps):
        action = np.argmax(qtable[state, :])
        new_state, reward, done, info = env.step(action)
        env.render()
        time.sleep(0.5)
        
        if done:
            print('Number of steps', step)
            break
        state = new_state
    
env.close()